dependencies {
	implementation project(':hotketok-common-service')
	implementation project(':hotketok-jpa-service')

	// Spring Cloud Eureka
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	// OpenFeign
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	// Kafka
	implementation 'org.springframework.kafka:spring-kafka'

	// lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// H2
	runtimeOnly 'com.h2database:h2'

	//MySQL
	runtimeOnly 'com.mysql:mysql-connector-j'

	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
