server:
  port: 8098

spring:
  application:
    name: notice-service

  # ===== H2 콘솔 =====
  h2:
    console:
      enabled: true
      path: /h2-console

  # ===== 데이터소스 =====
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/notice
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  datasource:
    url: jdbc:h2:file:~/notice
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # ===== JPA =====
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    hostname: chatting-service
    preferIpAddress: true
  client:
    registry-fetch-interval-seconds: 3
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.SQL: debug
    com.hotketok: info

client:
  house-service:
    url: http://localhost:8090
  user-service:
    url: http://localhost:8088