server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: requestform-service
              uri: lb://requestform-service
              predicates:
                - Path=/api/requestform-service/**
                - Method=GET,POST,PUT,DELETE

            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth-service/**
                - Method=GET,POST,PUT,DELETE


eureka:
  instance:
    hostname: apigateway-service
    preferIpAddress: true
  client:
    registry-fetch-interval-seconds: 3
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

