configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

dependencies {
	implementation project(':hotketok-common-service')
	implementation project(':hotketok-jpa-service')

	// SMS 서비스
	implementation 'net.nurigo:sdk:4.3.0'

	// Spring Cloud Eureka
	implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'

	// Spring Cloud Kubernetes Discovery Client
	implementation 'org.springframework.cloud:spring-cloud-starter-kubernetes-client'

	// Spring Cloud Kubernetes Config Client
	implementation 'org.springframework.cloud:spring-cloud-starter-kubernetes-client-config'

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

	// OpenFeign
	implementation 'org.springframework.cloud:spring-cloud-starter-openfeign'

	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// DevTool
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// H2
	runtimeOnly 'com.h2database:h2'

	// MySQL
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	// Redis
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.security:spring-security-test'
}

