server:
  port: 8087

spring:
  application:
    name: house-service
  cloud:
    kubernetes:
      config:
        enabled: false

  # ===== H2 콘솔 =====
  h2:
    console:
      enabled: true
      path: /h2-console

  # ===== 데이터소스 =====
  datasource:
    url: jdbc:h2:tcp://localhost/~/house
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # ===== JPA =====
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    hostname: house-service
    preferIpAddress: true
  client:
    registry-fetch-interval-seconds: 3
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.hibernate.SQL: debug

client:
  user-service:
    url: http://localhost:8084 # user-service의 주소
  infra-service:
    url: http://localhost:8081 # infra-service의 주소